apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - additional-config/namespace.yaml

helmCharts:
  - name: metal-lb
    repo: https://metal-lb.github.io/metal-lb/
    #version: 0.1.0 to install the latest version
    namespace: metal-lb
    releaseName: metal-lb
