apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clickstack
  namespace: observability
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "hyperdx.cloudhaven.work"
      http:
        paths:
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: clickstack-app
                port:
                  number: 3000