apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clickstack
  namespace: observability
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
    - host: hyperdx.cloudhaven.work
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: clickstack-api
                port:
                  number: 8080
    - host: hyperdx-ingest.cloudhaven.work
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: clickstack-ingest
                port:
                  number: 80
