# global:
#   storageClassName: longhorn

clickhouse:
  replicaCount: 2
  resources:
    limits:
      cpu: 500m
  persistence:
    enabled: true
    size: 50Gi

mongodb:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
  persistence:
    enabled: true
    dataSize: 20Gi

apikey: "85e3592f-912e-483c-ad2d-53ba8f5279f4"

# hyperdx:
#   useExistingConfigSecret: true
#   existingConfigSecret: "hyperdx-secret"
#   existingConfigConnectionsKey: "connections.json"
#   existingConfigSourcesKey: "sources.json"
#   frontendUrl: "https://hyperdx.cloudhaven.work"
#   ingress:
#     enabled: false