# global:
#   storageClassName: longhorn

clickhouse:
  replicaCount: 2
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
  persistence:
    enabled: true
    size: 50Gi

mongodb:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
  persistence:
    enabled: true
    dataSize: 20Gi

hyperdx:
  frontendUrl: "https://hyperdx.cloudhaven.work"
  ingress:
    enabled: true
    host: "hyperdx.cloudhaven.work"
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx