apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - issuer.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    releaseName: cert-manager
    namespace: cert-manager
    version: v1.15.1
    valuesInline:
      installCRDs: true
      prometheus:
        enabled: false