global:
  storageClassName: longhorn

clickhouse:
  replicaCount: 1
  affinity:
    nodeAffinity:  #to allow scheduling between workers
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
  resources:
    requests:
      cpu: 200m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 3.0Gi
  persistence:
    enabled: true
    size: 50Gi


mongodb:
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 384Mi
  persistence:
    enabled: true
    dataSize: 20Gi

otel:
  nodeSelector:
    opentelemetry.io/collector: "enabled"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

hyperdx:
  #useExistingConfigSecret: true
  #existingConfigSecret: "hyperdx-secret"
  # existingConfigConnectionsKey: "connections.json"
  # existingConfigSourcesKey: "sources.json"
  frontendUrl: "https://hyperdx.cloudhaven.work"
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      nginx.ingress.kubernetes.io/use-regex: "true"
    hosts:
      - host: "hyperdx.cloudhaven.work"
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: clickstack-app
                port:
                  number: 3000
  service:
    type: LoadBalancer
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

