apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qdrant

resources:
  - resources/namespace.yaml
  - resources/external-secret.yaml

helmCharts:
  - name: qdrant
    repo: https://qdrant.github.io/qdrant-helm
    releaseName: qdrant
    namespace: qdrant
    valuesFile: resources/values.yaml
